#!/bin/bash

set -e

# Find and select a PDF book, display only filename without extension
selected_book=$(find ~/data/books -maxdepth 1 -type f -name "*.pdf" -exec basename {} .pdf \; | fzf --prompt="Select book: " --height=40% --reverse)

if [[ -n $selected_book ]]; then
    # Open the selected book in zathura
    zathura ~/data/books/"$selected_book".pdf &
fi
